from fastapi import APIRouter, Request, BackgroundTasks
import requests
import os
from app.services.dialogflow_cx_client import detect_intent_texts

router = APIRouter()

TELEGRAM_BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN", "YOUR_TELEGRAM_BOT_TOKEN")
TELEGRAM_API_URL = f"https://api.telegram.org/bot{TELEGRAM_BOT_TOKEN}/sendMessage"

def send_telegram_message(chat_id: int, text: str):
    """Utility to send a message back to the Telegram User."""
    payload = {
        "chat_id": chat_id,
        "text": text
    }
    try:
        response = requests.post(TELEGRAM_API_URL, json=payload)
        response.raise_for_status()
    except Exception as e:
        print(f"Error sending message to Telegram: {e}")

@router.post("/telegram-webhook")
async def telegram_webhook(request: Request, background_tasks: BackgroundTasks):
    """
    Webhook to receive messages from Telegram, forward to Dialogflow CX,
    and respond back to the user asynchronously.
    """
    data = await request.json()
    
    if "message" in data and "text" in data["message"]:
        chat_id = data["message"]["chat"]["id"]
        user_text = data["message"]["text"]
        
        # Use Telegram chat_id as the Dialogflow session ID to keep conversation state
        session_id = str(chat_id)
        
        # Call Dialogflow CX integration
        df_responses = detect_intent_texts(session_id, user_text)
        
        # Send back every text response generated by Dialogflow
        for df_res in df_responses:
            background_tasks.add_task(send_telegram_message, chat_id, df_res.get("text", "Error parsing response"))

    return {"status": "ok"}
